/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.grupointegrado.view;

import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author higordealmeida
 */
public class MenuView extends javax.swing.JFrame {

    private CadastroClienteView telaCadastroCliente;
    private CadastroArtigoView telaCadastroArtigo;
    private CompraView telaCadastroCompra;
    private ConsultaCompraView telaConsultaCompra;
    private AlteraExcluiClienteView telaAlterarCliente;
    private SobreView telaSobre;
    
    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastroCliente = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuCadastroArtigo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuCadastroPedido = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuVerPedido = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuEditarClientes = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuCadastroCliente.setText("Cadastros");

        jMenuItem1.setText("Cadastrar Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuCadastroCliente.add(jMenuItem1);
        jMenuCadastroCliente.add(jSeparator1);

        jMenuCadastroArtigo.setText("Cadastrar Artigo");
        jMenuCadastroArtigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroArtigoActionPerformed(evt);
            }
        });
        jMenuCadastroCliente.add(jMenuCadastroArtigo);
        jMenuCadastroCliente.add(jSeparator2);

        jMenuCadastroPedido.setText("Cadastrar Pedido");
        jMenuCadastroPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroPedidoActionPerformed(evt);
            }
        });
        jMenuCadastroCliente.add(jMenuCadastroPedido);

        jMenuBar1.add(jMenuCadastroCliente);

        jMenu10.setText("Registros");

        jMenuVerPedido.setText("Ver Pedidos");
        jMenuVerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVerPedidoActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuVerPedido);
        jMenu10.add(jSeparator3);

        jMenuEditarClientes.setText("Ver / Editar Clientes");
        jMenuEditarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditarClientesActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuEditarClientes);

        jMenuBar1.add(jMenu10);

        jMenuSobre.setText("Sobre");

        jMenuItem7.setText("Sobre os Desenvolvedores");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenuSobre.add(jMenuItem7);

        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            telaCadastroCliente = new CadastroClienteView();
            telaCadastroCliente.setLocationRelativeTo(this);
            telaCadastroCliente.setVisible( true );
            
            telaCadastroCliente.addWindowListener( new java.awt.event.WindowAdapter() {
            
                public void windowClosed( WindowEvent e ) {
                
                }
            });
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuCadastroArtigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroArtigoActionPerformed
        telaCadastroArtigo = new CadastroArtigoView();
        telaCadastroArtigo.setLocationRelativeTo(this);
        telaCadastroArtigo.setVisible( true );
        telaCadastroArtigo.addWindowListener( new java.awt.event.WindowAdapter() {
            
            public void windowClosed( WindowEvent e ) {
                
            }
        });
    }//GEN-LAST:event_jMenuCadastroArtigoActionPerformed

    private void jMenuCadastroPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroPedidoActionPerformed
        telaCadastroCompra = new CompraView();
        telaCadastroCompra.setLocationRelativeTo(this);
        telaCadastroCompra.setVisible( true );
        telaCadastroCompra.addWindowListener( new java.awt.event.WindowAdapter() {
            
            public void windowClosed( WindowEvent e ) {
                
            }
        });
    }//GEN-LAST:event_jMenuCadastroPedidoActionPerformed

    private void jMenuVerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVerPedidoActionPerformed
        try {
            telaConsultaCompra = new ConsultaCompraView();
            telaConsultaCompra.setLocationRelativeTo(this);
            telaConsultaCompra.setVisible( true );
            telaConsultaCompra.addWindowListener( new java.awt.event.WindowAdapter() {
            
                public void windowClosed( WindowEvent e ) {
                
                }
            });
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuVerPedidoActionPerformed

    private void jMenuEditarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditarClientesActionPerformed
        try {
            telaAlterarCliente = new AlteraExcluiClienteView();
            telaAlterarCliente.setLocationRelativeTo(this);
            telaAlterarCliente.setVisible( true );
            telaAlterarCliente.addWindowListener( new java.awt.event.WindowAdapter() {
            
                public void windowClosed( WindowEvent e ) {
                
                }
            });
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jMenuEditarClientesActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        telaSobre = new SobreView();
        telaSobre.setLocationRelativeTo(this);
        telaSobre.setVisible( true );
        telaSobre.addWindowListener( new java.awt.event.WindowAdapter() {
            
                public void windowClosed( WindowEvent e ) {
                
                }
        });
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadastroArtigo;
    private javax.swing.JMenu jMenuCadastroCliente;
    private javax.swing.JMenuItem jMenuCadastroPedido;
    private javax.swing.JMenuItem jMenuEditarClientes;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JMenuItem jMenuVerPedido;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
